apiVersion: v1
kind: Namespace
metadata:
  name: greengrass
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: greengrass
  name: watcher
spec:
  selector:
    matchLabels:
      app: greengrass
  replicas: 1
  template:
    metadata:
      labels:
        app: greengrass
    spec:
      containers:
      - name: greengrass
        image: amazon/aws-iot-greengrass:latest
        env:
        - name: LOG_LEVEL
          value: "DEBUG"
        - name: GGC_ROOT_PATH
          value: "/greengrass/v2"
        - name: AWS_REGION
          value: "eu-central-1"
        - name: PROVISION
          value: "true"
        - name: THING_NAME
          value: "watcher"
        - name: THING_GROUP_NAME
          value: "k3s_gg_core_group"
        - name: TES_ROLE_NAME
          value: "k3s_TokenExchangeRole"
        - name: TES_ROLE_ALIAS_NAME
          value: "k3s_TokenExchangeRoleAlias"
        - name: COMPONENT_DEFAULT_USER
          value: "ggc_user:ggc_group"
        - name: DEPLOY_DEV_TOOLS
          value: "false"
        ports:
        - containerPort: 8883
        volumeMounts:
        - mountPath: /root/.aws
          name: credentials
        - mountPath: /greengrass/v2/logs
          name: logs
        - mountPath: /mnt/csv_files
          name: share
      volumes:
      - name: credentials
        hostPath:
          path: /home/alf/iot/share/aws/.aws
          type: Directory
      - name: logs
        hostPath:
          path: /home/alf/iot/greengrass/v2/logs 
          type: Directory
      - name: share
        hostPath:
          path: /mnt/csv_files
          type: Directory
